---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

inputs:
  - name: tarball

run:
  path: /bin/bash
  args:
    - -ec
    - |

      cd tarball 
      tar -xvf redis-fat.tgz